d2b_analytics_dbt:
  target: staging
  outputs:
    staging:
      type: postgres
      host: "34.89.230.185"
      user: "idowilek6169"
      password: "DhcdlXrJBW"
      port: 5432
      dbname: d2b_accessment # or database instead of dbname
      schema: "idowilek6169_staging"
      threads: 4
      keepalives_idle: 0 # default 0, indicating the system default. See below
      connect_timeout: 10 # default 10 seconds
      retries: 1  # default 1 retry on error/timeout when opening connections

    analytic:
      type: postgres
      host: "34.89.230.185"
      user: "idowilek6169"
      password: "DhcdlXrJBW"
      port: 5432
      dbname: d2b_accessment # or database instead of dbname
      schema: "idowilek6169_analytics"
      threads: 4
      keepalives_idle: 0 # default 0, indicating the system default. See below
      connect_timeout: 10 # default 10 seconds
      retries: 1  # default 1 retry on error/timeout when


# d2b_analytics_dbt:
#   target: staging
#   outputs:
#     staging:
#       type: postgres
#       host: "silly.db.elephantsql.com"
#       user: "dosmgkqh"
#       password: "fz1vpdY9kPNssUzw8N9569KcTpm2G0Yb"
#       port: 5432
#       dbname: "dosmgkqh" # or database instead of dbname
#       schema: "dbt_schema"
#       threads: 4
#       keepalives_idle: 0 # default 0, indicating the system default. See below
#       connect_timeout: 10 # default 10 seconds
#       retries: 1  # default 1 retry on error/timeout when opening connections

#     analytic:
#       type: postgres
#       host: "silly.db.elephantsql.com"
#       user: "dosmgkqh"
#       password: "fz1vpdY9kPNssUzw8N9569KcTpm2G0Yb"
#       port: 5432
#       dbname: "dosmgkqh" # or database instead of dbname
#       schema: "dbt_schema"
#       threads: 4
#       keepalives_idle: 0 # default 0, indicating the system default. See below
#       connect_timeout: 10 # default 10 seconds
#       retries: 1  # default 1 retry on error/timeout when