name: test airflow dag 

on: 
    push:
        branches: [ "master" ]

permissions:
    contents: read

jobs:
    build:
        runs-on: ubuntu-latest
    
        steps:
            - name: Checkout Code
              uses: actions/checkout@v2
        
            - name: Build the docker image
              run: |
                 docker build -t datatwobotsairflowimage:latest -f Dockerfile .
              working-directory: ${{ github.workspace }}
            - name: Run the docker image
              run: |
                 docker run run --it --rm datatwobotsairflowimage:latest -c "airflow trigger_dag dags.etl_abc_dag"
              working-directory: ${{ github.workspace }}
            - name: Run Airflow Dag and Pytest
              run: |
                docker exec -it datatwobot bash airflow trigger_dag dags.etl_abc_dag
                docker exec -it datatwobot pytest /app/test/test_load_data.py

            - name: Stop and Remove Services
              run: docker stop datatwobot && docker rm datatwobot
              # working-directory: ${{github.workspace}}

        # - name: Get Docker Container Name
        #   id: get_container_name
        #   run: |
        #     CONTAINER_NAME: $(docker ps --filter )

            

